%General Mission Analysis Tool(GMAT) Script
%Created: 2025-11-05 00:13:33


%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft DefaultSC;
DefaultSC.DateFormat = UTCGregorian;
DefaultSC.Epoch = '05 Nov 2025 00:00:00.000';
DefaultSC.CoordinateSystem = EarthMJ2000Eq;
DefaultSC.DisplayStateType = Keplerian;
DefaultSC.SMA = 6878;
DefaultSC.ECC = 0;
DefaultSC.INC = 97.40000000000001;
DefaultSC.RAAN = 0;
DefaultSC.AOP = 0;
DefaultSC.TA = 0;
DefaultSC.DryMass = 4;
DefaultSC.Cd = 2.2;
DefaultSC.Cr = 1.2;
DefaultSC.DragArea = 0.03;
DefaultSC.SRPArea = 0.02;
DefaultSC.SPADDragScaleFactor = 1;
DefaultSC.SPADSRPScaleFactor = 1;
DefaultSC.AtmosDensityScaleFactor = 1;
DefaultSC.ExtendedMassPropertiesModel = 'None';
DefaultSC.NAIFId = -10001001;
DefaultSC.NAIFIdReferenceFrame = -9001001;
DefaultSC.OrbitColor = Red;
DefaultSC.TargetColor = Teal;
DefaultSC.OrbitErrorCovariance = [ 1e+70 0 0 0 0 0 ; 0 1e+70 0 0 0 0 ; 0 0 1e+70 0 0 0 ; 0 0 0 1e+70 0 0 ; 0 0 0 0 1e+70 0 ; 0 0 0 0 0 1e+70 ];
DefaultSC.CdSigma = 1e+70;
DefaultSC.CrSigma = 1e+70;
DefaultSC.Id = 'SatId';
DefaultSC.Attitude = CoordinateSystemFixed;
DefaultSC.SPADSRPInterpolationMethod = Bilinear;
DefaultSC.SPADSRPScaleFactorSigma = 1e+70;
DefaultSC.SPADDragInterpolationMethod = Bilinear;
DefaultSC.SPADDragScaleFactorSigma = 1e+70;
DefaultSC.AtmosDensityScaleFactorSigma = 1e+70;
DefaultSC.ModelFile = 'aura.3ds';
DefaultSC.ModelOffsetX = 0;
DefaultSC.ModelOffsetY = 0;
DefaultSC.ModelOffsetZ = 0;
DefaultSC.ModelRotationX = 0;
DefaultSC.ModelRotationY = 0;
DefaultSC.ModelRotationZ = 0;
DefaultSC.ModelScale = 1;
DefaultSC.AttitudeDisplayStateType = 'Quaternion';
DefaultSC.AttitudeRateDisplayStateType = 'AngularVelocity';
DefaultSC.AttitudeCoordinateSystem = EarthMJ2000Eq;
DefaultSC.EulerAngleSequence = '321';


%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;
DefaultProp_ForceModel.CentralBody = Earth;
DefaultProp_ForceModel.PrimaryBodies = {Earth};
DefaultProp_ForceModel.Drag = None;
DefaultProp_ForceModel.SRP = Off;
DefaultProp_ForceModel.RelativisticCorrection = Off;
DefaultProp_ForceModel.ErrorControl = RSSStep;
DefaultProp_ForceModel.GravityField.Earth.Degree = 4;
DefaultProp_ForceModel.GravityField.Earth.Order = 4;
DefaultProp_ForceModel.GravityField.Earth.StmLimit = 100;
DefaultProp_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
DefaultProp_ForceModel.GravityField.Earth.TideModel = 'None';

Create ForceModel Propagator1_ForceModel;
Propagator1_ForceModel.CentralBody = Earth;
Propagator1_ForceModel.PrimaryBodies = {Earth};
Propagator1_ForceModel.PointMasses = {Luna, Sun};
Propagator1_ForceModel.SRP = On;
Propagator1_ForceModel.RelativisticCorrection = Off;
Propagator1_ForceModel.ErrorControl = RSSStep;
Propagator1_ForceModel.GravityField.Earth.Degree = 10;
Propagator1_ForceModel.GravityField.Earth.Order = 10;
Propagator1_ForceModel.GravityField.Earth.StmLimit = 100;
Propagator1_ForceModel.GravityField.Earth.PotentialFile = 'JGM2.cof';
Propagator1_ForceModel.GravityField.Earth.TideModel = 'None';
Propagator1_ForceModel.SRP.Flux = 1367;
Propagator1_ForceModel.SRP.SRPModel = Spherical;
Propagator1_ForceModel.SRP.Nominal_Sun = 149597870.691;
Propagator1_ForceModel.Drag.AtmosphereModel = JacchiaRoberts;
Propagator1_ForceModel.Drag.HistoricWeatherSource = 'ConstantFluxAndGeoMag';
Propagator1_ForceModel.Drag.PredictedWeatherSource = 'ConstantFluxAndGeoMag';
Propagator1_ForceModel.Drag.CSSISpaceWeatherFile = 'SpaceWeather-All-v1.2.txt';
Propagator1_ForceModel.Drag.SchattenFile = 'SchattenPredict.txt';
Propagator1_ForceModel.Drag.F107 = 150;
Propagator1_ForceModel.Drag.F107A = 150;
Propagator1_ForceModel.Drag.MagneticIndex = 3;
Propagator1_ForceModel.Drag.SchattenErrorModel = 'Nominal';
Propagator1_ForceModel.Drag.SchattenTimingModel = 'NominalCycle';
Propagator1_ForceModel.Drag.DragModel = 'Spherical';

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;
DefaultProp.FM = DefaultProp_ForceModel;
DefaultProp.Type = RungeKutta89;
DefaultProp.InitialStepSize = 60;
DefaultProp.Accuracy = 9.999999999999999e-12;
DefaultProp.MinStep = 0.001;
DefaultProp.MaxStep = 2700;
DefaultProp.MaxStepAttempts = 50;
DefaultProp.StopIfAccuracyIsViolated = true;

Create Propagator Propagator1;
Propagator1.FM = Propagator1_ForceModel;
Propagator1.Type = RungeKutta89;
Propagator1.InitialStepSize = 60;
Propagator1.Accuracy = 9.999999999999999e-12;
Propagator1.MinStep = 0.001;
Propagator1.MaxStep = 2700;
Propagator1.MaxStepAttempts = 50;
Propagator1.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OrbitView DefaultOrbitView;
DefaultOrbitView.SolverIterations = Current;
DefaultOrbitView.UpperLeft = [ 0.002941176470588235 0 ];
DefaultOrbitView.Size = [ 0.5458823529411765 0.5371287128712872 ];
DefaultOrbitView.RelativeZOrder = 43;
DefaultOrbitView.Maximized = false;
DefaultOrbitView.Add = {DefaultSC, Earth};
DefaultOrbitView.CoordinateSystem = EarthMJ2000Eq;
DefaultOrbitView.DrawObject = [ true true ];
DefaultOrbitView.DataCollectFrequency = 1;
DefaultOrbitView.UpdatePlotFrequency = 50;
DefaultOrbitView.NumPointsToRedraw = 0;
DefaultOrbitView.ShowPlot = true;
DefaultOrbitView.MaxPlotPoints = 20000;
DefaultOrbitView.ShowLabels = true;
DefaultOrbitView.ViewPointReference = Earth;
DefaultOrbitView.ViewPointVector = [ 30000 0 0 ];
DefaultOrbitView.ViewDirection = Earth;
DefaultOrbitView.ViewScaleFactor = 1;
DefaultOrbitView.ViewUpCoordinateSystem = EarthMJ2000Eq;
DefaultOrbitView.ViewUpAxis = Z;
DefaultOrbitView.EclipticPlane = Off;
DefaultOrbitView.XYPlane = On;
DefaultOrbitView.WireFrame = Off;
DefaultOrbitView.Axes = On;
DefaultOrbitView.Grid = Off;
DefaultOrbitView.SunLine = Off;
DefaultOrbitView.UseInitialView = On;
DefaultOrbitView.StarCount = 7000;
DefaultOrbitView.EnableStars = On;
DefaultOrbitView.EnableConstellations = On;

Create GroundTrackPlot DefaultGroundTrackPlot;
DefaultGroundTrackPlot.SolverIterations = Current;
DefaultGroundTrackPlot.UpperLeft = [ 0.08235294117647059 0.5371287128712872 ];
DefaultGroundTrackPlot.Size = [ 0.3805882352941177 0.4443069306930693 ];
DefaultGroundTrackPlot.RelativeZOrder = 66;
DefaultGroundTrackPlot.Maximized = false;
DefaultGroundTrackPlot.Add = {DefaultSC};
DefaultGroundTrackPlot.DataCollectFrequency = 1;
DefaultGroundTrackPlot.UpdatePlotFrequency = 50;
DefaultGroundTrackPlot.NumPointsToRedraw = 0;
DefaultGroundTrackPlot.ShowPlot = true;
DefaultGroundTrackPlot.MaxPlotPoints = 20000;
DefaultGroundTrackPlot.CentralBody = Earth;
DefaultGroundTrackPlot.TextureMap = 'ModifiedBlueMarble.jpg';

Create ReportFile ReportFile1;
ReportFile1.SolverIterations = Current;
ReportFile1.UpperLeft = [ 0.08529411764705883 0.07301980198019802 ];
ReportFile1.Size = [ 0.7741176470588236 0.7908415841584159 ];
ReportFile1.RelativeZOrder = 73;
ReportFile1.Maximized = true;
ReportFile1.Filename = 'OrbitResults.csv';
ReportFile1.Precision = 10;
ReportFile1.Add = {DefaultSC.A1ModJulian, DefaultSC.EarthMJ2000Eq.X, DefaultSC.Earth.Altitude, DefaultSC.Earth.SMA, DefaultSC.EarthMJ2000Eq.INC, DefaultSC.EarthMJ2000Eq.VX, DefaultSC.Earth.Energy};
ReportFile1.WriteHeaders = true;
ReportFile1.LeftJustify = On;
ReportFile1.ZeroFill = Off;
ReportFile1.FixedWidth = true;
ReportFile1.Delimiter = ' ';
ReportFile1.ColumnWidth = 23;
ReportFile1.WriteReport = true;
ReportFile1.AppendToExistingFile = false;


%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;
Propagate Propagator1(DefaultSC) {DefaultSC.ElapsedDays = 1825, DefaultSC.Earth.Altitude = 120};
Report ReportFile1 DefaultSC.A1ModJulian DefaultSC.A1Gregorian DefaultSC.Earth.Altitude DefaultSC.EarthMJ2000Eq.INC DefaultSC.Earth.SMA DefaultSC.EarthMJ2000Eq.X DefaultSC.EarthMJ2000Eq.VX;
